apiVersion: v1
kind: Pod
metadata:
  name: pod-for-hpa
  namespace: default
  labels:
    app: hpa
spec:
  restartPolicy: Never
  containers:
  - name: autoscale
    image: registry.cn-shanghai.aliyuncs.com/breaking_wave/minik8s:v1
    ports:
        - containerPort: 8090
    resources:
      requests:
        memory: 102400000   #100M
        cpu: 1000000000
      limits:
        memory: 204800000   #200M
        cpu: 2000000000
