apiVersion: v1
kind: Replicaset
metadata:
  name: testReplica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: replica
  template:
    metadata:
      name: replicaPod
      labels:
        app: replica
    spec:
      containers:
      - name: replicaContainer
        image: docker.io/library/nginx
        ImagePullPolicy: IfNotPresent
