apiVersion: v1
kind: Pod
metadata:
  name: dns-nginx-pod
  labels:
    app: dns-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d/
    ports:
    - containerPort: 80
  volumes:
  - name: nginx-conf
    hostPath:
      path: /etc/dns/nginx/conf/