apiVersion: v1
kind: Pod
metadata:
  name: dns-nginx-server-pod
  labels:
    app: dns-nginx-server
spec:
  containers:
  - name: nginx
    image: nginx
    command:
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d/
    - name: nginx-html
      mountPath: /usr/share/nginx/html/
    - name: nginx-log
      mountPath: /var/log/nginx/
    ports:
    - containerPort: 80
  volumes:
  - name: nginx-conf
    hostPath:
      path: /master/dns/nginx/conf/
  - name: nginx-html
    hostPath:
      path: /master/dns/nginx/html/
  - name: nginx-log
    hostPath:
      path: /master/dns/nginx/log/