apiVersion: v1
kind: Pod
metadata:
  name: pod-example2
  namespace: mem-example
  labels:
    app: test
spec:
  restartPolicy: Never
  volumes:
  - name: sharedData
    hostPath:
      path: /data
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    ports:
        - containerPort: 8090
    resources:
      requests:
        memory: 100000000
      limits:
        memory: 200000000
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: sharedData
      mountPath: /etc/nginx/nginx.conf