apiVersion: v1
kind: Replica
metadata:
  name: testReplica-1
spec:
  replicas: 3
  selector:
    matchLabels:
      labelkey1: labelvalue1
      labelkey2: labelvalue2
  template:
    metadata:
      labels:
        labelkey1: labelvalue1
        labelkey2: labelvalue2
    spec:
      NodeName: ubuntu
      containers:
      - name: testContainer-1
        image: nginx:lastest
        ImagePullPolicy: IfNotPresent
