# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: minik8s

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - name: Build API-Server
      run: |
        go build  -o ./build/apiserver/apiserver ./pkg/apiserver/main/main.go 
        go build  -o ./build/kubelet/kubelet ./pkg/kubelet/main/main.go
        go build  -o ./build/kubectl/kubectl ./pkg/kubectl/main/main.go 

#    - name: Test
#      run: go test -v ./...